#!/usr/bin/env python3
"""
build_graph.py (S4) — compile the LLM proposals into committed graph state, idempotently.

The "code disposes" half of the split: deterministic, validated, idempotent.
  - Reads graph/proposals.json (the LLM-proposed layer, S3).
  - Applies reversible merges: a merged claim is folded into its canonical claim; both are
    RETAINED (merge is a link, not a delete — S0 gap #4). Merged claims are marked
    lifecycle-equivalent via `merged_into` and dropped from the active projection set, but kept
    in `retired_claims` so the merge is reversible.
  - PRESERVES human edits: any claim/edge already in graph/graph.json with owner=human (claims)
    or a human override is carried over and NOT overwritten by a re-extraction (S4 invariant).
  - Validates the result against schemas/edges.schema.json before writing.
  - IDEMPOTENT: building twice from the same proposals yields byte-identical graph.json
    (stable ordering, no dup accumulation).

Usage: python3 build_graph.py            (writes graph/graph.json; exit 1 on schema failure)
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import validate as V

PROPOSALS = os.path.join(HERE, "graph", "proposals.json")
GRAPH = os.path.join(HERE, "graph", "graph.json")
EDGES_SCHEMA = os.path.join(HERE, "schemas", "edges.schema.json")


def build():
    prop = json.load(open(PROPOSALS))

    # Preserve human-owned claims from a prior build (S4: manual edits survive regeneration).
    human_claims = {}
    if os.path.exists(GRAPH):
        prev = json.load(open(GRAPH))
        for c in prev.get("claims", []):
            if c.get("owner") == "human":
                human_claims[c["claim_id"]] = c

    # Index proposed claims; a human version overrides the machine proposal of the same id.
    claims = {}
    for c in prop.get("claims", []):
        c = dict(c)
        c.setdefault("owner", "machine")
        claims[c["claim_id"]] = c
    for cid, hc in human_claims.items():
        claims[cid] = hc  # human wins — never overwritten

    # Apply reversible merges: fold merged ids into canonical, retire (retain) the merged claims.
    retired = {}
    merges = prop.get("merges", [])
    for m in merges:
        for mid in m.get("merged", []):
            if mid in claims:
                retired[mid] = dict(claims.pop(mid), merged_into=m["canonical"], merge_id=m["merge_id"])

    # Edges whose endpoints were merged away get their endpoints remapped to canonical
    # (an edge to a retired claim is redirected, not dropped — preserves the relation).
    merged_to_canon = {mid: m["canonical"] for m in merges for mid in m.get("merged", [])}
    edges = []
    for e in prop.get("edges", []):
        e = dict(e)
        e["from"] = merged_to_canon.get(e["from"], e["from"])
        e["to"] = merged_to_canon.get(e["to"], e["to"])
        edges.append(e)

    # Stable ordering → byte-identical output across runs (idempotency).
    graph = {
        "_doc": "COMPILED brain-map graph state (S4). Generated by build_graph.py from "
                "proposals.json — do not hand-edit except to set a claim's owner=human (which "
                "the builder then preserves). Idempotent: rebuild yields identical bytes.",
        "model_version": prop.get("model_version"),
        "claims": sorted(claims.values(), key=lambda c: c["claim_id"]),
        "edges": sorted(edges, key=lambda e: int(e["edge_id"].split("-")[1])),
        "merges": sorted(merges, key=lambda m: m["merge_id"]),
        "retired_claims": sorted(retired.values(), key=lambda c: c["claim_id"]),
    }

    # Validate the active projection (claims/edges/merges) against the schema before writing.
    to_validate = {"claims": graph["claims"], "edges": graph["edges"], "merges": graph["merges"]}
    errs = V.validate(to_validate, json.load(open(EDGES_SCHEMA)))
    if errs:
        print(f"BUILD FAILED — {len(errs)} schema error(s):")
        for e in errs[:10]:
            print(f"  ✗ {e}")
        sys.exit(1)

    json.dump(graph, open(GRAPH, "w"), indent=2, ensure_ascii=False)
    print(f"Built graph.json: {len(graph['claims'])} active claims, {len(graph['edges'])} edges, "
          f"{len(graph['merges'])} merges, {len(graph['retired_claims'])} retired (reversible).")
    return graph


if __name__ == "__main__":
    build()
