#!/usr/bin/env python3
"""
render.py (S5) — regenerate projections from the committed graph state.

Everything here is a PURE FUNCTION of graph/graph.json + the paper/study records — no new
knowledge is introduced (C1: survey/map are render targets, not storage). Each rendered
artifact is stamped with the SHA-256 of the exact graph.json it was rendered from — the
projection-provenance atom (S0 gap #5) that makes the overall-DoD traceability checkable.

Subcommands:
  paper-map            → render/paper_map.md        (nodes: papers by topic + reading order)
  brain-map <claim>    → render/brain_map.md        (a claim-neighborhood, mermaid)
  survey <claim>       → render/survey.md           (a survey section, every sentence cited)
  all                  → all three (brain-map/survey centered on the top-degree synthesis claim)

Usage: python3 render.py all
"""
import glob
import hashlib
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
GRAPH = os.path.join(HERE, "graph", "graph.json")
OUT = os.path.join(HERE, "render")


def _graph_sha():
    return hashlib.sha256(open(GRAPH, "rb").read()).hexdigest()


def _load():
    return json.load(open(GRAPH))


def _papers():
    d = {}
    for f in glob.glob(os.path.join(HERE, "papers", "*.json")):
        p = json.load(open(f))
        d[p["paper_id"]] = p
    return d


def _studies():
    """paper_id -> (title, topics, reading_tier, reading_status) from study frontmatter."""
    out = {}
    for f in glob.glob(os.path.join(HERE, "studies", "*.md")):
        t = open(f).read()
        pid = re.search(r"^paper_id:\s*(\S+)", t, re.M)
        if not pid:
            continue
        topics = re.search(r"^topics:\s*\[(.*?)\]", t, re.M)
        tier = re.search(r"^reading_tier:\s*(\d)", t, re.M)
        status = re.search(r"^reading_status:\s*(\w+)", t, re.M)
        title = re.search(r"^#\s*Study\s*—\s*(.+)$", t, re.M)
        out[pid.group(1)] = {
            "title": title.group(1).strip() if title else pid.group(1),
            "topics": [x.strip() for x in topics.group(1).split(",")] if topics else [],
            "tier": int(tier.group(1)) if tier else 3,
            "status": status.group(1) if status else "?",
        }
    return out


def _provenance(kind):
    return (f"<!-- generated by render.py ({kind}) from graph.json@sha256:{_graph_sha()[:16]} "
            f"— regenerable; do not hand-edit -->\n")


def _passage_text(papers, paper_id, passage_id):
    for p in papers.get(paper_id, {}).get("passages", []):
        if p["passage_id"] == passage_id:
            return p["text"]
    return None


def render_paper_map():
    studies = _studies()
    by_topic = {}
    for pid, s in studies.items():
        for topic in s["topics"]:
            group = topic.split("/")[0]
            by_topic.setdefault(group, []).append((pid, s))
    lines = [_provenance("paper-map"), "# Paper Map — corpus by topic + reading order\n",
             "*A projection of the corpus (nodes). Topic membership is many-to-many; a paper "
             "appears under every topic group it carries (C2: topics are views, not a hierarchy).*\n"]
    for group in sorted(by_topic):
        lines.append(f"\n## {group}\n")
        # reading order = reading_tier ascending (T1 must-read first); dedup by paper_id
        seen = {}
        for pid, s in by_topic[group]:
            seen[pid] = s
        for pid, s in sorted(seen.items(), key=lambda x: x[1]["tier"]):
            lines.append(f"- **T{s['tier']}** [{s['status']}] {s['title']}  (`{pid}`)")
    open(os.path.join(OUT, "paper_map.md"), "w").write("\n".join(lines) + "\n")
    print("rendered render/paper_map.md")


def _neighborhood(g, center):
    claims = {c["claim_id"]: c for c in g["claims"]}
    nbr_edges = [e for e in g["edges"]
                 if e["lifecycle"] == "confirmed" and (e["from"] == center or e["to"] == center)]
    nodes = {center} | {e["from"] for e in nbr_edges} | {e["to"] for e in nbr_edges}
    return claims, nbr_edges, nodes


def render_brain_map(center):
    g = _load()
    claims, nbr_edges, nodes = _neighborhood(g, center)
    lines = [_provenance("brain-map"),
             f"# Brain Map — claim-neighborhood of `{center}`\n",
             "*A projection of the graph (edges). Only `confirmed` edges are shown "
             "(proposed/superseded excluded from the truth view).*\n", "```mermaid", "graph LR"]
    for nid in sorted(nodes):
        label = claims.get(nid, {}).get("statement", nid)[:60].replace('"', "'")
        lines.append(f'  {nid.replace("-", "_")}["{nid}: {label}"]')
    for e in nbr_edges:
        lines.append(f'  {e["from"].replace("-", "_")} -->|{e["rel"]}| {e["to"].replace("-", "_")}')
    lines.append("```")
    open(os.path.join(OUT, "brain_map.md"), "w").write("\n".join(lines) + "\n")
    print(f"rendered render/brain_map.md (center {center}, {len(nodes)} nodes, {len(nbr_edges)} edges)")


def render_survey(center):
    g = _load()
    papers = _papers()
    claims = {c["claim_id"]: c for c in g["claims"]}
    # the survey section = the center claim + everything that `supports` it (confirmed), each
    # sentence traceable to a claim id and, where the claim is extraction, to a source passage.
    supporting = [e["from"] for e in g["edges"]
                  if e["to"] == center and e["rel"] == "supports" and e["lifecycle"] == "confirmed"]
    lines = [_provenance("survey"),
             f"# Survey section — {claims.get(center, {}).get('statement', center)}\n",
             "*Generated from committed graph state. Every substantive sentence traces to a claim "
             "id; extraction claims further cite a source passage (C1/traceability DoD).*\n",
             f"**Thesis ({center}).** {claims.get(center, {}).get('statement', '')} "
             f"*(inference; confidence {claims.get(center, {}).get('confidence', '?')})*\n",
             "**Supporting evidence:**\n"]
    for cid in supporting:
        c = claims.get(cid, {})
        cite = ""
        for ev in c.get("evidence", []):
            txt = _passage_text(papers, ev["paper_id"], ev["passage_id"])
            if txt:
                cite = f' — source [{ev["paper_id"]} {ev["passage_id"]}]: "{txt}"'
                break
        lines.append(f"- {c.get('statement','')} *({cid}, {c.get('evidence_tier','?')})*{cite}")
    open(os.path.join(OUT, "survey.md"), "w").write("\n".join(lines) + "\n")
    print(f"rendered render/survey.md (center {center}, {len(supporting)} supporting claims)")


def _default_center(g):
    # top-degree synthesis claim among confirmed edges
    deg = {}
    for e in g["edges"]:
        if e["lifecycle"] == "confirmed":
            deg[e["to"]] = deg.get(e["to"], 0) + 1
    return max(deg, key=deg.get) if deg else g["claims"][0]["claim_id"]


def main():
    os.makedirs(OUT, exist_ok=True)
    if len(sys.argv) < 2:
        print(__doc__); sys.exit(2)
    cmd = sys.argv[1]
    if cmd == "paper-map":
        render_paper_map()
    elif cmd == "brain-map":
        render_brain_map(sys.argv[2])
    elif cmd == "survey":
        render_survey(sys.argv[2])
    elif cmd == "all":
        g = _load()
        center = _default_center(g)
        render_paper_map()
        render_brain_map(center)
        render_survey(center)
        print(f"projection provenance: graph.json@sha256:{_graph_sha()[:16]}")
    else:
        print(__doc__); sys.exit(2)


if __name__ == "__main__":
    main()
